#!/usr/bin/env python3
"""
Prescriptive Phase 3: The Fields Property Positioning Playbook
===============================================================
Assembles all research (internal forensics + external research) into
archetype-specific selling playbooks.
"""

import json, os
from datetime import datetime

OUTPUT_DIR = "/home/fields/Fields_Orchestrator/output/positioning_research"

def load_json(path):
    try:
        with open(path) as f:
            return json.load(f)
    except:
        return {}

def main():
    # Load all data
    p3_arch = load_json(f"{OUTPUT_DIR}/phase_3/study_3_3_property_archetypes.json")
    p3_tiers = load_json(f"{OUTPUT_DIR}/phase_3/study_3_1_price_tiers.json")
    p4_agencies = load_json(f"{OUTPUT_DIR}/phase_4/study_4_2_agency_scorecard.json")
    forensics = load_json(f"{OUTPUT_DIR}/prescriptive/phase_0/study_0_1_outperformers.json")
    fast_slow = load_json(f"{OUTPUT_DIR}/prescriptive/phase_0/study_0_2_fast_vs_slow.json")
    agency_arch = load_json(f"{OUTPUT_DIR}/prescriptive/phase_0/study_0_3_agency_archetype.json")
    descriptions = load_json(f"{OUTPUT_DIR}/prescriptive/phase_0/study_0_4_descriptions.json")
    photos = load_json(f"{OUTPUT_DIR}/prescriptive/phase_0/study_0_5_photos.json")
    p8_seasonal = load_json(f"{OUTPUT_DIR}/phase_8/study_8_1_seasonal.json")
    p2_water = load_json(f"{OUTPUT_DIR}/phase_2/study_2_3_water.json")
    p7_streets = load_json(f"{OUTPUT_DIR}/phase_7/study_7_2_streets.json")

    md = []
    md.append("# THE FIELDS PROPERTY POSITIONING PLAYBOOK")
    md.append("## How to Sell Any Home in Our Target Market")
    md.append(f"### v2.0 | {datetime.now().strftime('%Y-%m-%d')} | Based on 2,153 sold properties + external research")
    md.append("")
    md.append("---")
    md.append("")

    # ── PART 1: UNIVERSAL PRINCIPLES ────────────────────────────────────
    md.append("# PART 1: UNIVERSAL PRINCIPLES")
    md.append("")
    md.append("## The 3 Things That Actually Drive Sale Price")
    md.append("")
    md.append("### 1. Location (suburb + street)")
    md.append("- 67% $/sqm variance between cheapest and most expensive suburb")
    md.append("- Within Burleigh Waters alone, streets range from -40% to +38% vs suburb median")
    md.append("- Water views add +45% in BW, +16% in VL, +6% in Robina")
    md.append("- **This is fixed. You can't change it. But you CAN position it.**")
    md.append("")
    md.append("### 2. Size (floor area + lot size)")
    md.append("- Strongest single predictor of price (r=0.68-0.79)")
    md.append("- Every extra square metre of internal floor area = $6,900-$9,500 depending on suburb")
    md.append("- **Implication:** Accurately measure and prominently feature floor area in every listing")
    md.append("")
    md.append("### 3. Bedroom count")
    md.append("- Each bedroom adds $255,000-$607,000 depending on suburb and starting count")
    md.append("- 3→4 bed jump is worth more than any renovation")
    md.append("- **Implication:** If a room CAN be a bedroom (study, office), present it as a bedroom option")
    md.append("")

    md.append("## The 5 Things That DON'T Drive $/sqm (Counter-Intuitive)")
    md.append("")
    md.append("1. **Renovation level** — In Robina and VL, fully renovated homes sell for LOWER $/sqm than original condition. Exception: BW, where full reno adds +14% $/sqm.")
    md.append("2. **Kitchen finishes** — Island bench, stone benchtops show no statistically significant $/sqm impact (p>0.1)")
    md.append("3. **Pool** — Only +0.6% to +3.7% $/sqm premium. Not significant. Pools are a price-tier MARKER, not a value DRIVER.")
    md.append("4. **Condition score** — Near-zero correlation with $/sqm. Better condition = higher-priced properties, but not higher VALUE per sqm.")
    md.append("5. **Corner lots** — Actually a DISCOUNT (-14% in Robina and BW, p=0.01). More road exposure, less privacy.")
    md.append("")
    md.append("**Why this matters for positioning:** Don't lead with kitchen finishes or renovation quality. Lead with location, size, and configuration. The market doesn't pay more per sqm for a stone benchtop — it pays more for an extra bedroom, water views, and the right street.")
    md.append("")

    md.append("## What Drives Speed of Sale")
    md.append("")
    md.append("**The honest answer: price drives speed, not quality.**")
    md.append("")
    md.append("- Properties priced 10%+ below cohort median sell in 16 days (Robina) vs 28-29 days at market")
    md.append("- Higher condition/presentation scores = SLOWER sales (r=+0.13), because they're proxies for higher price")
    md.append("- Pool adds +7.5 days (higher price, smaller buyer pool)")
    md.append("- **The only controllable speed lever is pricing.** Everything else is noise.")
    md.append("")
    md.append("### Campaign Timeline Best Practice")
    md.append("- **Days 1-14:** Peak engagement window. Maximum inquiry.")
    md.append("- **Days 14-30:** Serious buyers emerging. Most sales close here.")
    md.append("- **Day 30-45:** Fading engagement. If no offers, reassess pricing.")
    md.append("- **Day 45+:** One meaningful price reduction (5%+ minimum). Do NOT do small incremental drops.")
    md.append("- **Day 60+:** Stale listing stigma. Consider withdrawing and relisting with fresh positioning.")
    md.append("")

    # ── PART 2: THE BUYER ────────────────────────────────────────────────
    md.append("---")
    md.append("# PART 2: UNDERSTANDING THE BUYER")
    md.append("")
    md.append("## How Buyers Find and Choose Properties")
    md.append("")
    md.append("### The Click Decision (external research: REA, NAR, PropTrack)")
    md.append("1. **Hero photo** — 85% of buyers say photos are the most important element. The first image gets 95% of attention.")
    md.append("2. **Price** — 72% of buyers skip listings without a price displayed. 55% say price is their #1 priority.")
    md.append("3. **Headline** — Story-driven headlines outperform feature lists. But photos and price do the heavy lifting.")
    md.append("")
    md.append("### Photography Rules (evidence-based)")
    md.append("- Professional photography: +118% more online views (VHT Studios)")
    md.append("- **Optimal photo count: 22-27 images** (Zillow). <9 photos = 20x less likely to sell within 60 days. >28 = diminishing returns.")
    md.append("- **Twilight photography: +50% more views**, up to 3x more showings")
    md.append("- Our data: In VL, 80+ photos = fastest sales (16d). In BW, <20 photos = fastest (11d, likely original/land-value properties).")
    md.append("- **Recommendation:** 20-30 high-quality images for standard properties. Twilight hero shot for premium ($1.5M+).")
    md.append("")
    md.append("### The Buyer Journey")
    md.append("- 97% of searches start online (NAR 2024)")
    md.append("- Average buyer inspects 2-4 properties in person (AU data)")
    md.append("- Search duration: 2-6 months")
    md.append("- Average 40 minutes per portal session")
    md.append("- **Implication:** The listing MUST sell the property before the buyer visits. By the time they're at the open home, they're already emotionally engaged (or not).")
    md.append("")
    md.append("### Buyer Segments by Archetype (from our floor_plan_analysis)")
    md.append("")
    md.append("| Archetype | Primary Buyer | Median Price (BW) | What They Care About |")
    md.append("|-----------|--------------|-------------------|---------------------|")
    md.append("| Standard family home | Families | $1,530,000 | Space, schools, safety, yard |")
    md.append("| Family entertainer + pool | Families, entertainers | $2,335,000 | Outdoor living, pool, alfresco |")
    md.append("| Premium waterfront | Families, multigenerational | $2,405,000 | Water views, lifestyle, status |")
    md.append("| Compact starter/downsizer | Couples, small families, retirees | $1,218,000 | Low maintenance, location, value |")
    md.append("| Renovated family home | Families | $2,250,000 | Move-in ready, quality finishes |")
    md.append("| Original large block | Families, renovators | $2,125,000 | Land value, renovation potential |")
    md.append("| Duplex/villa | Couples, investors | $993,000 | Entry price, rental yield |")
    md.append("")

    # ── PART 3: PRICING STRATEGY ─────────────────────────────────────────
    md.append("---")
    md.append("# PART 3: PRICING STRATEGY")
    md.append("")
    md.append("## Private Treaty vs Auction")
    md.append("This is a **98% private treaty market.** Auction works ONLY for:")
    md.append("- Trophy/unique properties with demonstrable scarcity")
    md.append("- Properties with 3+ genuinely interested parties pre-campaign")
    md.append("- Premium waterfront entertainers in BW ($2.5M+)")
    md.append("- For everything else: private treaty outperforms on the Gold Coast.")
    md.append("")
    md.append("## Price Guide Approach")
    md.append("- **Price range** generates 20-30% more online engagement than 'Contact Agent' (PropTrack 2019)")
    md.append("- 72% of buyers skip listings without a price (REA 2024)")
    md.append("- **Recommendation:** Always display a price range. Set the bottom of the range at 95-100% of expected sale price. The range anchors buyers upward.")
    md.append("")
    md.append("## Price Positioning by Suburb")
    md.append("")
    md.append("| Suburb | Below Market (<-10%) | At Market | Above (+10%) |")
    md.append("|--------|---------------------|-----------|-------------|")
    md.append("| Robina | 16d median DOM | 28d | 29d |")
    md.append("| Varsity Lakes | 24d | 20d | 24d |")
    md.append("| Burleigh Waters | 30d | 30d | 37d |")
    md.append("")
    md.append("**Robina:** Pricing below market generates clear speed advantage (16d vs 28d). Competitive pricing works here.")
    md.append("**VL:** Pricing at market is actually fastest (20d). The market is efficient — buyers know value.")
    md.append("**BW:** Pricing position has less effect (30d vs 37d). Premium buyers are less price-sensitive, but the pool is smaller.")
    md.append("")

    # ── PART 4: PRE-SALE IMPROVEMENTS ────────────────────────────────────
    md.append("---")
    md.append("# PART 4: PRE-SALE IMPROVEMENTS")
    md.append("")
    md.append("## The Honest Truth About Renovation ROI")
    md.append("")
    md.append("**Our data says:** Renovation does NOT add $/sqm value in Robina or VL. In BW, fully renovated adds +14% $/sqm but takes 3x longer to sell (30d vs 11d for original).")
    md.append("")
    md.append("**External research says:** Fresh paint (up to 5% value add), landscaping (up to 20% perceived value), minor kitchen refresh (~77% ROI) are the best returns.")
    md.append("")
    md.append("**The academic evidence says:** Staging influences perceived livability but does NOT significantly increase willingness to pay (Lane et al., peer-reviewed).")
    md.append("")
    md.append("## What to Spend On (Cost-Effective)")
    md.append("1. **Fresh paint** — Highest ROI, lowest cost. Neutral tones. Every property.")
    md.append("2. **Landscaping/curb appeal** — Up to 20% perceived value improvement. Mow, mulch, trim, plant colour.")
    md.append("3. **Deep clean** — Professional clean including windows, carpets, grout. Non-negotiable.")
    md.append("4. **Declutter** — Remove 50% of personal items. Create space perception.")
    md.append("5. **Minor repairs** — Fix leaking taps, cracked tiles, door handles. Signals 'well-maintained'.")
    md.append("")
    md.append("## What NOT to Spend On (Low ROI)")
    md.append("1. **Full kitchen renovation** — ~57% ROI. Costs $35K, adds ~$20K. Buyers may not like your taste.")
    md.append("2. **Full bathroom renovation** — ~75% ROI. Better than kitchen but still not profitable.")
    md.append("3. **Pool installation** — Our data shows pools add only 0.6-3.7% $/sqm premium. Cost $40-80K. DON'T install pre-sale.")
    md.append("4. **Over-renovation for the street** — Spending $100K on a property in a $1.2M street won't make it a $1.5M property.")
    md.append("")
    md.append("## Staging Recommendation")
    md.append("- Professional styling MAY reduce DOM by up to 30% and add 1-10% to price (industry claims; academic evidence is weaker)")
    md.append("- **Worth it for:** Vacant properties, premium tier ($1.5M+), properties with poor furnishing")
    md.append("- **Not worth it for:** Well-furnished occupied homes, entry-level properties, original-condition land-value plays")
    md.append("- **Cost:** Typically 1-2% of listing price ($12-20K on a $1.2M property)")
    md.append("")

    # ── PART 5: LISTING COPY ─────────────────────────────────────────────
    md.append("---")
    md.append("# PART 5: LISTING COPY STRATEGY")
    md.append("")
    md.append("## What Our Data Shows About Description Patterns")
    md.append("")
    md.append("### Opening Pattern Performance")
    md.append("- **Lifestyle narrative** (70% of all listings) — Standard DOM, standard outcomes. This is the default.")
    md.append("- **Luxury aspirational** (15%) — Higher prices (correctly targets premium tier). Works for $1.5M+.")
    md.append("- **Urgency** (10-13%) — Mixed results. Works in Robina (16.5d DOM) but NOT in BW (33d). Premium buyers resist pressure.")
    md.append("- **Factual/specs-heavy** (2%) — Rare but interesting: fastest DOM in BW (20.5d). Suits buyers who've already decided on the suburb and want data.")
    md.append("")
    md.append("### Feature Hierarchy (What Gets Mentioned First)")
    md.append("- Robina: 'family' (#1), 'living' (#2), 'spacious' (#3)")
    md.append("- VL: 'family' (#1), 'living' (#2), 'spacious'/'bedroom'/'water' tied (#3)")
    md.append("- BW: **'water' (#1)** — water is the defining feature even in descriptions")
    md.append("")
    md.append("### Recommendations by Archetype")
    md.append("")
    md.append("**Standard Family Home ($1.2-1.5M):**")
    md.append("- Lead with: family lifestyle + space + location benefits")
    md.append("- Tone: warm lifestyle narrative")
    md.append("- Mention: bedroom count, living zones, outdoor space, school zone")
    md.append("- Avoid: urgency language, 'investor' or 'first home' (signals low-end)")
    md.append("")
    md.append("**Premium Waterfront Entertainer ($2M+):**")
    md.append("- Lead with: water views + outdoor entertaining + lifestyle")
    md.append("- Tone: luxury aspirational OR factual/data-driven (both work)")
    md.append("- Mention: water views first, pool, alfresco, floor area")
    md.append("- Avoid: urgency ('don't miss' — 102.5d median DOM in BW for urgency-opening listings)")
    md.append("")
    md.append("**Original Large Block ($1.5-2M):**")
    md.append("- Lead with: land size, location value, potential")
    md.append("- Tone: factual — these buyers know what they want")
    md.append("- Mention: lot size, zoning, renovation potential, comparable sales of renovated homes nearby")
    md.append("- Avoid: overselling the existing structure. Buyers are buying the dirt.")
    md.append("")
    md.append("**Compact Starter/Downsizer (<$1.2M):**")
    md.append("- Lead with: location + value + low maintenance")
    md.append("- Tone: practical, value-focused")
    md.append("- Mention: proximity to amenities, ease of living, rental yield potential")
    md.append("- Avoid: 'luxury', 'prestige' (mismatched expectations)")
    md.append("")

    # ── PART 6: AGENCY SELECTION ─────────────────────────────────────────
    md.append("---")
    md.append("# PART 6: AGENCY SELECTION BY ARCHETYPE")
    md.append("")
    md.append("## STAR Agencies (Sell Fast + Above Market)")
    md.append("")

    for suburb in ["robina", "varsity_lakes", "burleigh_waters"]:
        agencies = p4_agencies.get(suburb, {}).get("agencies", [])
        stars = [a for a in agencies if a.get("quadrant", "").startswith("STAR")]
        md.append(f"### {suburb.replace('_',' ').title()}")
        if stars:
            for a in stars[:4]:
                prem = a.get("median_premium_vs_cohort_pct", 0)
                dom = a.get("median_dom", 0)
                md.append(f"- **{a['agency']}**: +{prem:.1f}% above cohort, {dom:.0f}d DOM ({a['sales']} sales)")
        md.append("")

    md.append("## Best Agency by Property Archetype")
    md.append("")
    for suburb in ["robina", "varsity_lakes", "burleigh_waters"]:
        md.append(f"### {suburb.replace('_',' ').title()}")
        md.append("| Archetype | Best Agency | Sales | Premium |")
        md.append("|-----------|-----------|-------|---------|")
        for arch, agencies in sorted(agency_arch.get(suburb, {}).items()):
            if agencies:
                a = agencies[0]
                prem = f"+{a['median_premium']:.1f}%" if a.get("median_premium") is not None else "-"
                md.append(f"| {arch} | {a['agency']} | {a['sales']} | {prem} |")
        md.append("")

    # ── PART 7: TIMING ──────────────────────────────────────────────────
    md.append("---")
    md.append("# PART 7: WHEN TO SELL")
    md.append("")
    md.append("| Suburb | Best Price Month | Fastest Selling | Peak Volume |")
    md.append("|--------|-----------------|----------------|-------------|")
    for suburb in ["robina", "varsity_lakes", "burleigh_waters"]:
        r = p8_seasonal.get(suburb, {})
        md.append(f"| {suburb.replace('_',' ').title()} | {r.get('best_price_month', '-')} | {r.get('fastest_dom_month', '-')} | {r.get('peak_volume_month', '-')} |")
    md.append("")
    md.append("**General Gold Coast pattern:** Sep-Nov = peak volume (spring selling season). May = fastest DOM. July = quietest month.")
    md.append("")
    md.append("**Premium property timing:** March is the best price AND fastest DOM month for BW. List in autumn, not spring (less competition in the premium segment).")
    md.append("")

    # ── PART 8: CONFIDENCE DASHBOARD ─────────────────────────────────────
    md.append("---")
    md.append("# PART 8: CONFIDENCE DASHBOARD")
    md.append("")
    md.append("Every recommendation has a confidence level:")
    md.append("")
    md.append("| Recommendation | Confidence | Source | Sample |")
    md.append("|----------------|-----------|--------|--------|")
    md.append("| Location is #1 price driver | HIGH | Our data (2,153 records) | Full population |")
    md.append("| Floor area correlation with price | HIGH | Our data (r=0.68-0.79) | 1,662 records |")
    md.append("| Bedroom marginal values | HIGH | Our data | 100+ per combo |")
    md.append("| Water view premiums | HIGH | Our data (p<0.01) | 2,142 records |")
    md.append("| Renovation doesn't add $/sqm (Robina/VL) | HIGH | Our data (contradicts industry) | 500+ records |")
    md.append("| Agency STAR rankings | MEDIUM | Our data (3-66 sales per agency) | DOM subset |")
    md.append("| Optimal photo count 22-27 | MEDIUM | Zillow + our data | External + 2,153 |")
    md.append("| Twilight photography +50% views | MEDIUM | VHT Studios/Virtuance | Industry data |")
    md.append("| Staging adds 1-10% | LOW | Industry claims vs academic null | Biased sources |")
    md.append("| Description tone → DOM | LOW | Our data (truncated descriptions) | Pattern-level |")
    md.append("| Price range > Contact Agent | MEDIUM | PropTrack 2019 | Portal data |")
    md.append("| Pre-sale paint ROI 5% | MEDIUM | Multiple AU sources | Industry consensus |")
    md.append("| Campaign 21-35 days optimal | MEDIUM | CoreLogic + REA | Portal engagement data |")
    md.append("| Price reduction 5%+ at 4 weeks | MEDIUM | Domain 2020 + CoreLogic | Transaction data |")
    md.append("")

    # ── WHAT WE STILL DON'T KNOW ─────────────────────────────────────────
    md.append("---")
    md.append("# WHAT WE STILL DON'T KNOW")
    md.append("")
    md.append("1. **Buyer-side data** — We know what sold, not WHY buyers chose it. Survey data needed.")
    md.append("2. **Marketing channel ROI** — Which channels (portal premium, social, signage) actually drive inquiry?")
    md.append("3. **Open home effectiveness** — Private inspection vs open home. No data.")
    md.append("4. **Specific staging ROI for our market** — Academic evidence says minimal; industry says 5-10%. Need local A/B testing.")
    md.append("5. **Negotiation tactics** — How to handle multiple offers, when to accept vs hold. Experience-based, not data-driven.")
    md.append("6. **Long-term market cycles** — 12-month window may not represent trends.")
    md.append("")

    md.append("---")
    md.append(f"*The Fields Property Positioning Playbook v2.0 | {datetime.now().strftime('%Y-%m-%d')} | 2,153 properties, 50+ studies, 8 suburbs, 3 external research streams*")

    path = f"{OUTPUT_DIR}/POSITIONING_PLAYBOOK_v2.md"
    with open(path, "w") as f:
        f.write("\n".join(md))
    print(f"Playbook written to: {path}")
    print(f"Word count: {len(' '.join(md).split())}")
    return "\n".join(md)


if __name__ == "__main__":
    content = main()
    print("\n" + "=" * 60)
    print("PLAYBOOK v2.0 COMPLETE")
    print("=" * 60)
