#!/usr/bin/env python3
"""
Stage 5 — Suburb Contextualisation (the core three).

For each of Robina / Varsity Lakes / Burleigh Waters, one synthesis pass that answers: given
this cycle's live topics + audience psychology + our internal suburb data, what is the honest,
data-grounded context for a homeowner/buyer HERE? This is where national/QLD themes are
translated into local evidence. Bound by the valuation design envelope ($1M-$2M; suppress point
figures outside it), the no-single-valuation-in-headlines rule, and the union-median
reliability flags.

Output artifact: suburb_context/<suburb>_<cycle>.md  (×3)
Zero-output assertion (Rule 7b): a suburb with live listings but zero contextual output RAISES.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys

import mce_common as mc

PROMPT = """\
{rules}

TASK: Write the current market CONTEXT for a homeowner or buyer in {suburb_name}, southern Gold
Coast, as at {cycle}. This is the raw material our editorial team will turn into public content
(articles, market pages) — so it must be honest, data-grounded, and free of advice or prediction.

## This suburb's Fields data is SUPPLIED — use verbatim, never look it up
{suburb_pack}

Constraints specific to this suburb layer:
- Valuation design envelope is $1,000,000-$2,000,000 for detached houses. Do not state a single
  point valuation as the home's worth in any heading; use ranges/gaps.
- A quarter flagged reliable=false cannot support a quarter-on-quarter move — say so.
- Sales VOLUME is a more dependable signal than any single quarterly median.

## This cycle's researched themes (bottom lines from our dossiers — build on these, cite them)
{dossier_lines}

## Current audience psychology (from our Stage-3 brief — informs emphasis, not claims)
{psych_lines}

## Structure (markdown)
1. The one-paragraph context: what is actually happening in {suburb_name} right now, in plain
   terms, grounded in the supplied data.
2. How the national/Queensland themes above land HERE specifically (translate each relevant
   theme to local evidence; if a theme does not apply to this suburb, say so).
3. What buyers here are weighing; what owners here are weighing (use the psychology brief for
   emphasis, the supplied data for facts).
4. The honest caveats — data limitations, capture rate, reliability flags, envelope.
{section9}

Return the complete context as markdown. Ground every number in the supplied pack; research the
web only to connect the macro themes, never to restate this suburb's figures.
"""


def _suburb_pack_md(pack: dict, suburb: str) -> str:
    """Extract just this suburb's block from the fields price pack + counts + demand."""
    md = pack.get("fields_price_pack_md", "")
    name = mc.DISPLAY_NAMES.get(suburb, suburb)
    # pull the "## <Name>" section out of the combined pack
    blocks = re.split(r"(?=^## )", md, flags=re.M)
    mine = next((b for b in blocks if b.strip().startswith(f"## {name}")), "")
    counts = pack.get("listing_counts", {}).get(suburb, {})
    lines = [mine.strip(),
             f"\nLive listings: {counts.get('for_sale')} for sale, {counts.get('sold')} sold "
             f"on record."]
    intent = (pack.get("search_intent") or {}).get("suburbs", {}).get(suburb)
    if intent:
        lines.append(f"Local search interest: {intent.get('total_queries')} queries; "
                     f"questions asked include: "
                     f"{'; '.join(intent.get('questions') or [])[:3] if isinstance(intent.get('questions'), str) else '; '.join((intent.get('questions') or [])[:3])}.")
    return "\n".join(lines)


def _dossier_lines(cycle: str) -> str:
    """Bottom-line blockquotes from this cycle's refreshed dossiers."""
    out = []
    for slug_file in sorted(os.listdir(mc.TOPICS_DIR)):
        if not slug_file.endswith(".md"):
            continue
        with open(os.path.join(mc.TOPICS_DIR, slug_file), encoding="utf-8") as fh:
            txt = fh.read()
        bl = re.findall(r"^>\s?(.*)$", txt, re.M)
        title = (re.search(r"^#\s*(.+)$", txt, re.M) or [None, slug_file[:-3]])[1]
        if bl:
            out.append(f"- **{title.strip()}**: {' '.join(x.strip() for x in bl)[:400]}")
    return "\n".join(out) or "(no dossiers available this cycle)"


def _psych_lines(cycle: str, limit: int = 2500) -> str:
    meta = mc.load_artifact(cycle, "psychology_brief.json")
    if not meta:
        return "(no psychology brief this cycle)"
    path = os.path.join(mc.ROOT, meta["path"])
    if not os.path.exists(path):
        return "(psychology brief file missing)"
    with open(path, encoding="utf-8") as fh:
        return fh.read()[:limit]


HEADER = """\
# {name} — market context

*Cycle {cycle} · source material for editorial, not published copy · generated by the Market
Context Engine (Stage 5). {name} figures were SUPPLIED from live Fields data, not researched.*

---

"""


def contextualise(suburb: str, cycle: str, pack: dict, *, model=None, timeout=1500) -> dict:
    name = mc.DISPLAY_NAMES.get(suburb, suburb)
    prompt = PROMPT.format(
        rules=mc.HONESTY_RULES + "\n\n" + mc.OUTPUT_DISCIPLINE, suburb_name=name, cycle=cycle,
        suburb_pack=_suburb_pack_md(pack, suburb),
        dossier_lines=_dossier_lines(cycle),
        psych_lines=_psych_lines(cycle),
        section9=("5. " + mc.SECTION9_INSTRUCTION),
    )
    res = mc.run_claude(prompt, model=model or mc.MODEL_DEEP, timeout=timeout, max_turns=26)
    md = mc.extract_markdown(res["text"])
    if len(md) < 1200:
        raise RuntimeError(f"{suburb}: implausibly short context ({len(md)} chars)")

    os.makedirs(mc.SUBURB_DIR, exist_ok=True)
    path = os.path.join(mc.SUBURB_DIR, f"{suburb}_{cycle}.md")
    body = md.lstrip()
    if body.startswith("# "):
        body = body.split("\n", 1)[1].lstrip() if "\n" in body else ""
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(HEADER.format(name=name, cycle=cycle) + body)

    qa = mc.qa_scan(md)
    print(f"    ✓ Stage 5 [{suburb}]: {len(md)} chars (${res.get('cost')}), QA={len(qa)}",
          file=sys.stderr)
    return {"suburb": suburb, "path": os.path.relpath(path, mc.ROOT), "chars": len(md),
            "cost": res.get("cost"), "qa": qa, "has_section9": mc.has_section9(md)}


def run(cycle: str, *, only: list[str] | None = None, model=None, timeout=1500) -> dict:
    pack = mc.load_artifact(cycle, "internal_pack.json")
    if not pack:
        raise RuntimeError("Stage 5: internal_pack.json missing — run Stage 0 first")
    subs = only or mc.TARGET_SUBURBS
    done, failures = [], []
    for s in subs:
        try:
            done.append(contextualise(s, cycle, pack, model=model, timeout=timeout))
        except Exception as e:
            failures.append(f"{s}: {type(e).__name__}: {e}")
            print(f"    ✗ Stage 5 [{s}]: {e}", file=sys.stderr)
    out = {"cycle": cycle, "done": len(done), "failures": failures, "results": done}
    mc.save_artifact(cycle, "stage5_results.json", out)
    # Rule 7b: a suburb with live listings that produced nothing is a failure.
    live = pack.get("total_live_listings", 0)
    if subs and not done and live > 0:
        raise RuntimeError(f"Stage 5 produced 0 suburb contexts despite {live} live listings; "
                           f"failures={failures}")
    print(f"    ✓ Stage 5: {len(done)}/{len(subs)} suburb contexts", file=sys.stderr)
    return out


def main():
    ap = argparse.ArgumentParser(description="MCE Stage 5 — suburb contextualisation")
    ap.add_argument("--cycle", default=mc.cycle_id())
    ap.add_argument("--only", action="append", choices=mc.TARGET_SUBURBS)
    ap.add_argument("--model", default=None)
    a = ap.parse_args()
    out = run(a.cycle, only=a.only, model=a.model)
    print(json.dumps({"done": out["done"], "failures": out["failures"]}, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
