#!/usr/bin/env python3
"""
Stage 3 — Psychology Synthesis (buyer + seller, per suburb).

Produces a current psychological read of BOTH sides of our audience, grounded in measured
signals (search-intent fears/questions, Reddit sentiment, our own listing data) plus live web
research on rates/sentiment/news — NOT vibes. Folds in the existing homeowner_mindset brief as
the seller base (its §9 honesty block is binding) and extends it to the buyer side, which the
mindset brief does not cover.

Output artifacts:
  * briefs/current/<cycle>_psychology.md
  * data/<cycle>/psychology_brief.json  (metadata + summary for downstream stages)
Zero-output assertion (Rule 7b): if neither the mindset brief nor the demand signals are
available, RAISE — a psychology brief with no evidence base is worse than none.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys

import mce_common as mc

PROMPT = """\
{rules}

TASK: Produce an INTERNAL strategy brief on the current PSYCHOLOGY of our audience in the
southern Gold Coast (Robina, Varsity Lakes, Burleigh Waters), as at {cycle}. Two sides:
SELLERS (pre-listing homeowners) and BUYERS. This is NOT public content; it informs which
facts we surface and how we frame them. It never licenses advice, prediction or persuasion.

## Our own numbers and demand signals are SUPPLIED — never look them up, never restate from memory
{pack_md}

## The current seller-psychology base (refresh + extend it, do not just repeat it)
The following is our standing homeowner-mindset brief. Treat its "What we deliberately did NOT
conclude" section as binding. Update anything the latest rate decision / news cycle has moved,
and ADD the buyer side, which it does not cover.

--- MINDSET BRIEF (excerpt) ---
{mindset_excerpt}
--- END ---

## Research the moving parts (web)
Use web search for: the RBA cash rate and next-decision expectations (note where forecasters
DISAGREE — conflict drives paralysis), consumer sentiment and house-price expectations
(Westpac-Melbourne Institute), first-home-buyer / lending conditions, rental market, and what
property media aimed at this audience is currently saying. Cite URLs and dates.

## Tag every claim: [VERIFIED] (checked against a cited source), [FIELDS] (from the supplied
pack), [INFERRED] (a reasonable behavioural read, not independently confirmed — be generous
with this tag).

## Structure (markdown)
1. The defining tension in each side's head right now (sellers; buyers).
2. SELLERS: what they are worried about (ranked by emotional weight, with evidence), and what
   actually motivates them to list.
3. BUYERS: what they are worried about and what they are searching for / hesitating on — use
   the supplied demand signals (fears: crash/price-drop; questions: "should I buy now").
4. Per-suburb nuance (Robina, Varsity Lakes, Burleigh Waters) where the supplied data supports
   it — never invent a suburb difference the data does not show.
5. Messaging implications for a data-led business bound by no-advice/no-prediction rules.
{section9}

Where the brief's messaging section and its "did NOT conclude" section disagree, the latter
wins. Where external sources and OUR supplied data disagree, OUR data wins for these suburbs.
Return the complete brief as markdown. Depth over brevity.
"""


def _mindset_excerpt(limit: int = 6000) -> str:
    try:
        from homeowner_mindset import latest_report
        rep = latest_report()
    except Exception:
        rep = None
    if not rep:
        return "(no standing mindset brief found — build the seller side from scratch.)"
    text = rep["text"]
    # keep the executive summary + section 9 if we can find them, else head-truncate
    s9 = re.search(r"(#+\s*9?\.?\s*What we deliberately did NOT conclude.*)", text, re.I | re.S)
    head = text[:limit]
    if s9:
        return head + "\n\n...[§9 verification section]...\n\n" + s9.group(1)[:3000]
    return head


def build_prompt(cycle: str) -> str:
    pack = mc.load_artifact(cycle, "internal_pack.json")
    if not pack:
        raise RuntimeError("Stage 3: internal_pack.json missing — run Stage 0 first")
    from mce_stage0_data import render_pack_md
    return PROMPT.format(
        rules=mc.HONESTY_RULES + "\n\n" + mc.OUTPUT_DISCIPLINE, cycle=cycle,
        pack_md=render_pack_md(pack, include_demand=True),
        mindset_excerpt=_mindset_excerpt(),
        section9=("6. " + mc.SECTION9_INSTRUCTION),
    )


HEADER = """\
# Audience Psychology — Southern Gold Coast (buyers + sellers)

*Cycle {cycle} · INTERNAL strategy brief, not public content · generated by the Market
Context Engine (Stage 3). Suburb figures + demand signals were SUPPLIED from live Fields data,
not researched.*

---

"""


def run(cycle: str, *, model: str | None = None, timeout: int = 1800,
        dry_run: bool = False) -> dict:
    pack = mc.load_artifact(cycle, "internal_pack.json")
    intent = (pack or {}).get("search_intent") or {}
    have_mindset = "no standing mindset brief" not in _mindset_excerpt(200)
    if not intent.get("available") and not have_mindset:
        raise RuntimeError("Stage 3: no demand signals AND no mindset brief — no evidence base")

    prompt = build_prompt(cycle)
    if dry_run:
        print(prompt)
        return {"dry_run": True}

    res = mc.run_claude(prompt, model=model or mc.MODEL_DEEP, timeout=timeout, max_turns=30)
    md = mc.extract_markdown(res["text"])
    if len(md) < 2500:
        raise RuntimeError(f"Stage 3: implausibly short psychology brief ({len(md)} chars)")
    if not mc.has_section9(md):
        raise RuntimeError("Stage 3: psychology brief missing the mandatory §9 "
                           "'did NOT conclude' section")

    os.makedirs(mc.BRIEFS_CUR, exist_ok=True)
    path = os.path.join(mc.BRIEFS_CUR, f"{cycle}_psychology.md")
    body = md.lstrip()
    if body.startswith("# "):          # drop the model's own H1 so the provenance header owns the top
        body = body.split("\n", 1)[1].lstrip() if "\n" in body else ""
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(HEADER.format(cycle=cycle) + body)

    meta = {"cycle": cycle, "path": os.path.relpath(path, mc.ROOT),
            "chars": len(md), "words": len(md.split()), "cost": res.get("cost"),
            "has_section9": True,
            "qa": mc.qa_scan(md)}
    mc.save_artifact(cycle, "psychology_brief.json", meta)
    print(f"    ✓ Stage 3: psychology brief {meta['words']} words "
          f"(${res.get('cost')}), QA issues={len(meta['qa'])}", file=sys.stderr)
    return meta


def main():
    ap = argparse.ArgumentParser(description="MCE Stage 3 — psychology synthesis")
    ap.add_argument("--cycle", default=mc.cycle_id())
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--model", default=None)
    a = ap.parse_args()
    out = run(a.cycle, model=a.model, dry_run=a.dry_run)
    if not a.dry_run:
        print(json.dumps(out, indent=2, default=str))
    return 0


if __name__ == "__main__":
    sys.exit(main())
