#!/usr/bin/env python3
"""
extract_intro_for_site.py — split matrix-intro.html into the three parts React needs.

The intro is authored as a complete standalone HTML document, which is the right
way to iterate on it. The React deck cannot use a document — it needs the markup
to render, the stylesheet to load, and the script to run, separately.

ONE TRANSFORMATION IS APPLIED, AND IT IS NOT COSMETIC.

The standalone document locks itself with an UNCONDITIONAL

    html, body { height: 100%; overflow: hidden; }

which is correct when the intro owns the whole document and catastrophic in a
React app: the rule is global and permanent, so after the intro hands off the
deck cannot be scrolled at all. It is rewritten to apply only under
`html.intro-locked`, which the host adds while the intro is on screen and
intro.js removes at hand-off. The conditional rule already exists in the source
directly below it — this only stops the unconditional one shadowing it forever.

Run after any change to matrix-intro.html:
    python3 extract_intro_for_site.py
"""
from __future__ import annotations

import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
DEST = Path("/home/fields/Feilds_Website/01_Website/public/off-market-v3")

src = (HERE / "matrix-intro.html").read_text()
style = re.search(r"<style>(.*?)</style>", src, re.S).group(1)
scripts = re.findall(r"<script>(.*?)</script>", src, re.S)
body = re.search(r"<body[^>]*>(.*?)</body>", src, re.S).group(1)
markup = re.sub(r"<script>.*?</script>", "", body, flags=re.S).strip()

# The one transformation. Scoped, not deleted: the intro still needs the black
# background and the full-height stage while it is running.
lock = re.compile(r"^\s*html,\s*body\s*\{([^}]*)\}", re.M)
match = lock.search(style)
if not match:
    raise SystemExit("the `html, body { … }` rule is gone — re-read the source "
                     "before assuming this extractor is still correct")
style = lock.sub(
    "  /* Scoped by extract_intro_for_site.py: unconditional here would leave the\n"
    "     whole site unscrollable after the intro hands off. */\n"
    "  html.intro-locked, html.intro-locked body {" + match.group(1) + "}",
    style, count=1)
if re.search(r"^\s*html,\s*body\s*\{", style, re.M):
    raise SystemExit("more than one unconditional html/body rule — scope them all")

DEST.mkdir(parents=True, exist_ok=True)
(DEST / "intro.css").write_text(
    "/* intro.css — the matrix recognition sequence.\n"
    " *\n"
    " * GENERATED by intro/extract_intro_for_site.py from matrix-intro.html.\n"
    " * Edit the source there and re-run; do not edit this file.\n"
    " *\n"
    " * Global on purpose: intro.js addresses its elements by literal id\n"
    " * (#stage, #rain, #alarm) and toggles `.intro-locked` on <html>.\n"
    " */\n" + style.strip() + "\n")
(DEST / "intro.js").write_text(
    "/* intro.js — GENERATED from matrix-intro.html. Unchanged code.\n"
    " * Reads window.__FIELDS_INTRO ({street, locality, tokens}) and fires\n"
    " * `fields:intro-done` at hand-off, releasing `.intro-locked` first.\n"
    " */\n" + "\n".join(s.strip() for s in scripts) + "\n")
(DEST / "intro-markup.html").write_text(markup + "\n")

print(f"intro.css {len(style.splitlines())} lines · intro.js "
      f"{sum(len(s.splitlines()) for s in scripts)} lines · markup "
      f"{len(markup.splitlines())} lines -> {DEST}")
print("page lock scoped to html.intro-locked")
