#!/usr/bin/env python3
"""
Google Indexing API + Search Console integration for Fields Estate.

Usage:
  # One-time auth setup (generates refresh token):
  python3 scripts/google_indexing.py auth

  # Submit all property URLs for indexing:
  python3 scripts/google_indexing.py submit-all

  # Submit a specific URL:
  python3 scripts/google_indexing.py submit https://fieldsestate.com.au/property/ABC123

  # Check indexing status of key pages:
  python3 scripts/google_indexing.py status

  # Submit only new/changed URLs since last run:
  python3 scripts/google_indexing.py submit-new

Requires:
  pip install google-auth google-auth-oauthlib google-api-python-client pymongo

  Environment variables (in .env):
    GOOGLE_INDEXING_REFRESH_TOKEN — OAuth2 refresh token (generated by 'auth' command)
    GOOGLE_ADS_CLIENT_ID — OAuth2 client ID (reused from Google Ads)
    GOOGLE_ADS_CLIENT_SECRET — OAuth2 client secret (reused from Google Ads)
    COSMOS_CONNECTION_STRING — for database queries
"""

import os
import sys
import json
import time
from datetime import datetime, timezone

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------
SITE_URL = "https://fieldsestate.com.au"
SCOPES = [
    "https://www.googleapis.com/auth/indexing",
    "https://www.googleapis.com/auth/webmasters.readonly",
]
TARGET_SUBURBS = ["robina", "varsity_lakes", "burleigh_waters"]

# Rate limits: Indexing API allows 200 requests/day
DAILY_QUOTA = 200
BATCH_DELAY = 1.0  # seconds between requests


def load_env():
    """Load .env file."""
    env_path = os.path.join(os.path.dirname(__file__), "..", ".env")
    if os.path.exists(env_path):
        with open(env_path) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    key, _, value = line.partition("=")
                    os.environ.setdefault(key.strip(), value.strip())


def get_credentials():
    """Get OAuth2 credentials from refresh token."""
    from google.oauth2.credentials import Credentials

    client_id = os.environ.get("GOOGLE_ADS_CLIENT_ID")
    client_secret = os.environ.get("GOOGLE_ADS_CLIENT_SECRET")
    refresh_token = os.environ.get("GOOGLE_INDEXING_REFRESH_TOKEN")

    if not all([client_id, client_secret, refresh_token]):
        print("ERROR: Missing credentials. Run 'python3 scripts/google_indexing.py auth' first.")
        sys.exit(1)

    creds = Credentials(
        token=None,
        refresh_token=refresh_token,
        client_id=client_id,
        client_secret=client_secret,
        token_uri="https://oauth2.googleapis.com/token",
        scopes=SCOPES,
    )
    return creds


# ---------------------------------------------------------------------------
# Auth command
# ---------------------------------------------------------------------------
def cmd_auth():
    """One-time OAuth2 authorization flow."""
    from google_auth_oauthlib.flow import InstalledAppFlow

    client_id = os.environ.get("GOOGLE_ADS_CLIENT_ID")
    client_secret = os.environ.get("GOOGLE_ADS_CLIENT_SECRET")

    if not client_id or not client_secret:
        print("ERROR: Set GOOGLE_ADS_CLIENT_ID and GOOGLE_ADS_CLIENT_SECRET in .env first.")
        sys.exit(1)

    # Build client config from env vars (same OAuth client as Google Ads)
    client_config = {
        "installed": {
            "client_id": client_id,
            "client_secret": client_secret,
            "auth_uri": "https://accounts.google.com/o/oauth2/auth",
            "token_uri": "https://oauth2.googleapis.com/token",
            "redirect_uris": ["http://localhost"],
        }
    }

    flow = InstalledAppFlow.from_client_config(client_config, scopes=SCOPES)

    # Generate the auth URL for manual flow (no local server on VM)
    auth_url, _ = flow.authorization_url(
        access_type="offline",
        prompt="consent",
    )

    print("\n" + "=" * 60)
    print("GOOGLE INDEXING API — ONE-TIME AUTHORIZATION")
    print("=" * 60)
    print("\n1. Open this URL in your browser:\n")
    print(auth_url)
    print("\n2. Sign in with will.simpson@blueoceans.com.au")
    print("3. Grant access to 'Fields Estate Ads' app")
    print("4. Copy the authorization code from the redirect URL")
    print("   (it's the 'code' parameter after http://localhost?code=...)")
    print()

    code = input("Paste the authorization code here: ").strip()

    if not code:
        print("No code provided. Aborting.")
        sys.exit(1)

    # Exchange code for tokens
    flow.fetch_token(code=code)
    creds = flow.credentials

    print(f"\nRefresh token: {creds.refresh_token}")
    print("\nAdd this to your .env file:")
    print(f"GOOGLE_INDEXING_REFRESH_TOKEN={creds.refresh_token}")

    # Auto-append to .env
    env_path = os.path.join(os.path.dirname(__file__), "..", ".env")
    with open(env_path, "a") as f:
        f.write(f"\n# Google Indexing API (added {datetime.now().strftime('%Y-%m-%d')})\n")
        f.write(f"GOOGLE_INDEXING_REFRESH_TOKEN={creds.refresh_token}\n")
    print(f"\nAutomatically appended to {env_path}")
    print("Auth complete. You can now run: python3 scripts/google_indexing.py submit-all")


# ---------------------------------------------------------------------------
# Submit URLs
# ---------------------------------------------------------------------------
def submit_url(service, url, action="URL_UPDATED"):
    """Submit a single URL to the Indexing API."""
    body = {"url": url, "type": action}
    try:
        response = service.urlNotifications().publish(body=body).execute()
        return {"url": url, "status": "ok", "notifyTime": response.get("urlNotificationMetadata", {}).get("latestUpdate", {}).get("notifyTime")}
    except Exception as e:
        return {"url": url, "status": "error", "error": str(e)}


def get_property_urls():
    """Fetch all property URLs from the database."""
    from pymongo import MongoClient

    uri = os.environ.get("COSMOS_CONNECTION_STRING")
    if not uri:
        print("ERROR: COSMOS_CONNECTION_STRING not set.")
        return []

    client = MongoClient(uri, serverSelectionTimeoutMS=10000)
    db = client["Gold_Coast"]
    urls = []

    for suburb in TARGET_SUBURBS:
        try:
            coll = db[suburb]
            # For-sale properties
            for doc in coll.find({"listing_status": "for_sale"}, {"_id": 1}):
                urls.append(f"{SITE_URL}/property/{doc['_id']}")
            # Sold properties
            for doc in coll.find({"listing_status": "sold"}, {"_id": 1}):
                urls.append(f"{SITE_URL}/sold/{doc['_id']}")
        except Exception as e:
            print(f"  Warning: error querying {suburb}: {e}")

    client.close()
    return urls


def cmd_submit_all():
    """Submit all property URLs to the Indexing API."""
    from googleapiclient.discovery import build

    creds = get_credentials()
    service = build("indexing", "v3", credentials=creds)

    # Get all property URLs
    print("Fetching property URLs from database...")
    urls = get_property_urls()

    # Add static pages
    static_urls = [
        f"{SITE_URL}/",
        f"{SITE_URL}/for-sale",
        f"{SITE_URL}/recently-sold",
        f"{SITE_URL}/market-intelligence/Robina",
        f"{SITE_URL}/market-intelligence/Varsity-Lakes",
        f"{SITE_URL}/market-intelligence/Burleigh-Waters",
        f"{SITE_URL}/analyse",
        f"{SITE_URL}/why-fields",
    ]
    all_urls = static_urls + urls

    print(f"Found {len(all_urls)} URLs ({len(static_urls)} static + {len(urls)} properties)")

    if len(all_urls) > DAILY_QUOTA:
        print(f"WARNING: {len(all_urls)} URLs exceeds daily quota of {DAILY_QUOTA}.")
        print(f"Will submit first {DAILY_QUOTA} URLs (prioritizing static + for-sale).")
        all_urls = all_urls[:DAILY_QUOTA]

    # Submit URLs
    results = {"ok": 0, "error": 0, "errors": []}
    for i, url in enumerate(all_urls):
        result = submit_url(service, url)
        if result["status"] == "ok":
            results["ok"] += 1
        else:
            results["error"] += 1
            results["errors"].append(result)

        if (i + 1) % 10 == 0:
            print(f"  Submitted {i + 1}/{len(all_urls)} ({results['ok']} ok, {results['error']} errors)")

        time.sleep(BATCH_DELAY)

    print(f"\nDone. Submitted {results['ok']} URLs successfully, {results['error']} errors.")
    if results["errors"]:
        print("Errors:")
        for err in results["errors"][:10]:
            print(f"  {err['url']}: {err['error']}")


def cmd_submit(url):
    """Submit a single URL."""
    from googleapiclient.discovery import build

    creds = get_credentials()
    service = build("indexing", "v3", credentials=creds)

    result = submit_url(service, url)
    if result["status"] == "ok":
        print(f"Submitted: {url}")
        print(f"Notify time: {result.get('notifyTime')}")
    else:
        print(f"Error submitting {url}: {result['error']}")


def cmd_submit_new():
    """Submit only URLs that changed since last run."""
    from googleapiclient.discovery import build
    from pymongo import MongoClient

    state_file = os.path.join(os.path.dirname(__file__), "..", "logs", "indexing-last-run.json")

    # Load last run timestamp
    last_run = None
    if os.path.exists(state_file):
        with open(state_file) as f:
            data = json.load(f)
            last_run = data.get("last_run")

    uri = os.environ.get("COSMOS_CONNECTION_STRING")
    if not uri:
        print("ERROR: COSMOS_CONNECTION_STRING not set.")
        return

    client = MongoClient(uri, serverSelectionTimeoutMS=10000)
    db = client["Gold_Coast"]
    urls = []

    query = {}
    if last_run:
        from datetime import datetime as dt
        query["last_updated"] = {"$gte": dt.fromisoformat(last_run)}
        print(f"Finding URLs updated since {last_run}...")
    else:
        print("No previous run found. Submitting all URLs (use submit-all for first run).")
        client.close()
        return cmd_submit_all()

    for suburb in TARGET_SUBURBS:
        try:
            coll = db[suburb]
            for doc in coll.find({**query, "listing_status": "for_sale"}, {"_id": 1}):
                urls.append(f"{SITE_URL}/property/{doc['_id']}")
            for doc in coll.find({**query, "listing_status": "sold"}, {"_id": 1}):
                urls.append(f"{SITE_URL}/sold/{doc['_id']}")
        except Exception as e:
            print(f"  Warning: error querying {suburb}: {e}")

    client.close()

    if not urls:
        print("No new/changed URLs since last run.")
    else:
        print(f"Found {len(urls)} new/changed URLs.")
        creds = get_credentials()
        service = build("indexing", "v3", credentials=creds)

        ok = 0
        for i, url in enumerate(urls[:DAILY_QUOTA]):
            result = submit_url(service, url)
            if result["status"] == "ok":
                ok += 1
            if (i + 1) % 10 == 0:
                print(f"  Submitted {i + 1}/{len(urls)}")
            time.sleep(BATCH_DELAY)
        print(f"Submitted {ok}/{len(urls)} URLs.")

    # Save state
    os.makedirs(os.path.dirname(state_file), exist_ok=True)
    with open(state_file, "w") as f:
        json.dump({"last_run": datetime.now(timezone.utc).isoformat()}, f)


def cmd_status():
    """Check indexing status using Search Console API."""
    from googleapiclient.discovery import build

    creds = get_credentials()
    service = build("searchconsole", "v1", credentials=creds)

    site_url = "sc-domain:fieldsestate.com.au"
    # Try URL prefix if domain property doesn't work
    try:
        result = service.searchAnalytics().query(
            siteUrl=site_url,
            body={
                "startDate": "2026-03-01",
                "endDate": "2026-03-09",
                "dimensions": ["page"],
                "rowLimit": 25,
            }
        ).execute()
    except Exception:
        site_url = "https://fieldsestate.com.au/"
        result = service.searchAnalytics().query(
            siteUrl=site_url,
            body={
                "startDate": "2026-03-01",
                "endDate": "2026-03-09",
                "dimensions": ["page"],
                "rowLimit": 25,
            }
        ).execute()

    rows = result.get("rows", [])
    if not rows:
        print("No search analytics data yet. Google needs a few days to collect data after indexing.")
        return

    print(f"Search Console data for {site_url}:")
    print(f"{'Page':<60} {'Clicks':>7} {'Impressions':>12} {'CTR':>8} {'Position':>10}")
    print("-" * 100)
    for row in rows:
        page = row["keys"][0]
        clicks = row.get("clicks", 0)
        impressions = row.get("impressions", 0)
        ctr = row.get("ctr", 0)
        position = row.get("position", 0)
        print(f"{page:<60} {clicks:>7} {impressions:>12} {ctr:>7.1%} {position:>10.1f}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    load_env()

    if len(sys.argv) < 2:
        print("Usage: python3 scripts/google_indexing.py <command>")
        print("Commands: auth, submit-all, submit <url>, submit-new, status")
        sys.exit(1)

    command = sys.argv[1]

    if command == "auth":
        cmd_auth()
    elif command == "submit-all":
        cmd_submit_all()
    elif command == "submit":
        if len(sys.argv) < 3:
            print("Usage: python3 scripts/google_indexing.py submit <url>")
            sys.exit(1)
        cmd_submit(sys.argv[2])
    elif command == "submit-new":
        cmd_submit_new()
    elif command == "status":
        cmd_status()
    else:
        print(f"Unknown command: {command}")
        sys.exit(1)
