#!/usr/bin/env python3
"""
Google Indexing API + Search Console integration for Fields Estate.

Usage:
  # One-time auth setup (generates refresh token):
  python3 scripts/google_indexing.py auth

  # Submit all property URLs for indexing:
  python3 scripts/google_indexing.py submit-all

  # Submit a specific URL:
  python3 scripts/google_indexing.py submit https://fieldsestate.com.au/property/ABC123

  # Check indexing status of key pages:
  python3 scripts/google_indexing.py status

  # Submit only new/changed URLs since last run:
  python3 scripts/google_indexing.py submit-new

Requires:
  pip install google-auth google-auth-oauthlib google-api-python-client pymongo

  Environment variables (in .env):
    GOOGLE_INDEXING_REFRESH_TOKEN — OAuth2 refresh token (generated by 'auth' command)
    GOOGLE_ADS_CLIENT_ID — OAuth2 client ID (reused from Google Ads)
    GOOGLE_ADS_CLIENT_SECRET — OAuth2 client secret (reused from Google Ads)
    COSMOS_CONNECTION_STRING — for database queries
"""

import os
import sys
import json
import time
from datetime import datetime, timezone

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------
SITE_URL = "https://fieldsestate.com.au"
SCOPES = [
    "https://www.googleapis.com/auth/indexing",
    "https://www.googleapis.com/auth/webmasters",
]
TARGET_SUBURBS = ["robina", "varsity_lakes", "burleigh_waters"]

# Rate limits: Indexing API allows 200 requests/day
DAILY_QUOTA = 200
BATCH_DELAY = 1.0  # seconds between requests


def load_env():
    """Load .env file (python-dotenv, standardised 2026-07-23 — this script's own
    hand-rolled quote-stripping bug is exactly why: see fix-history 2026-07-22
    [GOOGLE-INDEXING-INVALIDURI])."""
    from dotenv import load_dotenv
    env_path = os.path.join(os.path.dirname(__file__), "..", ".env")
    load_dotenv(env_path, override=False)


SA_KEY_PATH = os.environ.get("GOOGLE_INDEXING_SA_KEY", "/home/fields/.gcp-indexing-sa.json")


def get_credentials():
    """Service-account credentials if available, else the legacy OAuth refresh token.

    A service account is the approach Google documents for the Indexing API and it is
    strictly better for a nightly server job: no consent screen, no refresh token to
    expire or be overwritten, no OAuth publishing-status restrictions.

    Both of the failures we hit came from the OAuth path:
      * `GOOGLE_INDEXING_REFRESH_TOKEN` was byte-identical to `GOOGLE_ADS_REFRESH_TOKEN`,
        i.e. an `adwords`-scoped token used to request `indexing` + `webmasters`, so every
        refresh returned `invalid_scope` — 757 URLs dropped over 9 nights
        (fix-history [INDEXING-SILENT-ZERO]).
      * Re-consenting then failed with `Error 403: access_denied`, because the OAuth client
        lives in project `fields-estate-ads` whose consent screen is not published for
        these sensitive scopes.

    The service account must be added as a **delegated owner** of the Search Console
    property, otherwise the API answers 403 `Permission denied`. That is the one step
    that cannot be automated from here.
    """
    from google.oauth2.credentials import Credentials

    if os.path.exists(SA_KEY_PATH):
        from google.oauth2 import service_account
        return service_account.Credentials.from_service_account_file(
            SA_KEY_PATH, scopes=SCOPES)

    client_id = os.environ.get("GOOGLE_ADS_CLIENT_ID")
    client_secret = os.environ.get("GOOGLE_ADS_CLIENT_SECRET")
    refresh_token = os.environ.get("GOOGLE_INDEXING_REFRESH_TOKEN")

    if refresh_token and refresh_token == os.environ.get("GOOGLE_ADS_REFRESH_TOKEN"):
        print("ERROR: GOOGLE_INDEXING_REFRESH_TOKEN is the same value as "
              "GOOGLE_ADS_REFRESH_TOKEN — an adwords-scoped token cannot request the "
              "indexing scope and will fail with invalid_scope on every call.\n"
              f"Fix: add the service-account key at {SA_KEY_PATH} (preferred), or mint a "
              "genuinely indexing-scoped refresh token.", file=sys.stderr)
        sys.exit(1)

    if not all([client_id, client_secret, refresh_token]):
        print("ERROR: Missing credentials. Run 'python3 scripts/google_indexing.py auth' first.")
        sys.exit(1)

    creds = Credentials(
        token=None,
        refresh_token=refresh_token,
        client_id=client_id,
        client_secret=client_secret,
        token_uri="https://oauth2.googleapis.com/token",
        scopes=SCOPES,
    )
    return creds


# ---------------------------------------------------------------------------
# Auth command
# ---------------------------------------------------------------------------
def cmd_auth():
    """One-time OAuth2 authorization flow."""
    from google_auth_oauthlib.flow import InstalledAppFlow

    client_id = os.environ.get("GOOGLE_ADS_CLIENT_ID")
    client_secret = os.environ.get("GOOGLE_ADS_CLIENT_SECRET")

    if not client_id or not client_secret:
        print("ERROR: Set GOOGLE_ADS_CLIENT_ID and GOOGLE_ADS_CLIENT_SECRET in .env first.")
        sys.exit(1)

    # Build client config from env vars (same OAuth client as Google Ads)
    client_config = {
        "installed": {
            "client_id": client_id,
            "client_secret": client_secret,
            "auth_uri": "https://accounts.google.com/o/oauth2/auth",
            "token_uri": "https://oauth2.googleapis.com/token",
            "redirect_uris": ["http://localhost"],
        }
    }

    flow = InstalledAppFlow.from_client_config(client_config, scopes=SCOPES)

    # Generate the auth URL for manual flow (no local server on VM)
    auth_url, _ = flow.authorization_url(
        access_type="offline",
        prompt="consent",
    )

    print("\n" + "=" * 60)
    print("GOOGLE INDEXING API — ONE-TIME AUTHORIZATION")
    print("=" * 60)
    print("\n1. Open this URL in your browser:\n")
    print(auth_url)
    print("\n2. Sign in with will.simpson@blueoceans.com.au")
    print("3. Grant access to 'Fields Estate Ads' app")
    print("4. Copy the authorization code from the redirect URL")
    print("   (it's the 'code' parameter after http://localhost?code=...)")
    print()

    code = input("Paste the authorization code here: ").strip()

    if not code:
        print("No code provided. Aborting.")
        sys.exit(1)

    # Exchange code for tokens
    flow.fetch_token(code=code)
    creds = flow.credentials

    print(f"\nRefresh token: {creds.refresh_token}")
    print("\nAdd this to your .env file:")
    print(f"GOOGLE_INDEXING_REFRESH_TOKEN={creds.refresh_token}")

    # Auto-append to .env
    env_path = os.path.join(os.path.dirname(__file__), "..", ".env")
    with open(env_path, "a") as f:
        f.write(f"\n# Google Indexing API (added {datetime.now().strftime('%Y-%m-%d')})\n")
        f.write(f"GOOGLE_INDEXING_REFRESH_TOKEN={creds.refresh_token}\n")
    print(f"\nAutomatically appended to {env_path}")
    print("Auth complete. You can now run: python3 scripts/google_indexing.py submit-all")


# ---------------------------------------------------------------------------
# Submit URLs
# ---------------------------------------------------------------------------
def submit_url(service, url, action="URL_UPDATED"):
    """Submit a single URL to the Indexing API."""
    body = {"url": url, "type": action}
    try:
        response = service.urlNotifications().publish(body=body).execute()
        return {"url": url, "status": "ok", "notifyTime": response.get("urlNotificationMetadata", {}).get("latestUpdate", {}).get("notifyTime")}
    except Exception as e:
        return {"url": url, "status": "error", "error": str(e)}


def get_property_urls():
    """Fetch all property URLs from the database."""
    from pymongo import MongoClient

    uri = os.environ.get("COSMOS_CONNECTION_STRING")
    if not uri:
        print("ERROR: COSMOS_CONNECTION_STRING not set.")
        return []

    client = MongoClient(uri, serverSelectionTimeoutMS=10000)
    db = client["Gold_Coast"]

    # Order matters: the caller (cmd_submit_all) caps submissions at DAILY_QUOTA
    # (200/day). The OLD ordering appended every suburb's listings in _id-ascending
    # (oldest-first) order, robina first — so the 200/day quota was consumed by
    # static pages + the oldest robina URLs, and (a) genuinely NEW editorial pages
    # sorted LAST and were never submitted, and (b) varsity_lakes / burleigh_waters
    # were never reached at all (robina alone has >200 URLs). That is the root cause
    # of "we publish ~100 new editorial pages and they get no organic traffic":
    # they were never submitted to Google's Indexing API. Fix: sort NEWEST-first by
    # last_updated (falling back to the ObjectId's own timestamp), and put for-sale
    # ahead of sold, so freshly-published listing pages are submitted first.
    def _recency(doc):
        v = doc.get("last_updated")
        if isinstance(v, datetime):
            return v if v.tzinfo else v.replace(tzinfo=timezone.utc)
        if isinstance(v, str):
            try:
                dtv = datetime.fromisoformat(v.replace("Z", "+00:00"))
                return dtv if dtv.tzinfo else dtv.replace(tzinfo=timezone.utc)
            except ValueError:
                pass
        return doc["_id"].generation_time  # ObjectId embeds creation time (tz-aware)

    for_sale, sold = [], []
    for suburb in TARGET_SUBURBS:
        try:
            coll = db[suburb]
            # EDITORIAL GATE: only submit for-sale pages that have passed the
            # editorial pipeline (ai_analysis.status == "published"). Without this
            # we pinged Google's Indexing API the same night a listing was scraped,
            # so Google indexed the fallback meta ("Property For Sale | Fields")
            # BEFORE the nightly editorial run wrote the real hook — then we had to
            # wait for a re-crawl to fix it. See fix-history 2026-07-24 (27 Florabella).
            for doc in coll.find({"listing_status": "for_sale", "ai_analysis.status": "published"}, {"_id": 1, "last_updated": 1}):
                for_sale.append((_recency(doc), f"{SITE_URL}/property/{doc['_id']}"))
            for doc in coll.find({"listing_status": "sold"}, {"_id": 1, "last_updated": 1}):
                sold.append((_recency(doc), f"{SITE_URL}/sold/{doc['_id']}"))
        except Exception as e:
            print(f"  Warning: error querying {suburb}: {e}")

    client.close()

    # Newest-first within each group; for-sale (live listings) ahead of sold.
    for_sale.sort(key=lambda t: t[0], reverse=True)
    sold.sort(key=lambda t: t[0], reverse=True)
    return [u for _, u in for_sale] + [u for _, u in sold]


def cmd_submit_all():
    """Submit all property URLs to the Indexing API."""
    from googleapiclient.discovery import build

    creds = get_credentials()
    service = build("indexing", "v3", credentials=creds)

    # Get all property URLs
    print("Fetching property URLs from database...")
    urls = get_property_urls()

    # Add static pages
    static_urls = [
        f"{SITE_URL}/",
        f"{SITE_URL}/for-sale",
        f"{SITE_URL}/recently-sold",
        f"{SITE_URL}/market-intelligence/Robina",
        f"{SITE_URL}/market-intelligence/Varsity-Lakes",
        f"{SITE_URL}/market-intelligence/Burleigh-Waters",
        f"{SITE_URL}/analyse-your-home",
        f"{SITE_URL}/why-fields",
    ]

    # Market metrics pages (SEO-critical — these target high-intent search queries)
    market_metrics_suburbs = ["Robina", "Varsity-Lakes", "Burleigh-Waters"]
    market_metrics_categories = ["sell-now", "buy", "crash-risk", "overview", "direction", "suburb-compare"]
    for suburb in market_metrics_suburbs:
        static_urls.append(f"{SITE_URL}/market-metrics/{suburb}")
        for cat in market_metrics_categories:
            static_urls.append(f"{SITE_URL}/market-metrics/{suburb}/{cat}")

    all_urls = static_urls + urls

    print(f"Found {len(all_urls)} URLs ({len(static_urls)} static + {len(urls)} properties)")

    if len(all_urls) > DAILY_QUOTA:
        print(f"WARNING: {len(all_urls)} URLs exceeds daily quota of {DAILY_QUOTA}.")
        print(f"Will submit first {DAILY_QUOTA} URLs (prioritizing static + for-sale).")
        all_urls = all_urls[:DAILY_QUOTA]

    # Submit URLs
    results = {"ok": 0, "error": 0, "errors": []}
    for i, url in enumerate(all_urls):
        result = submit_url(service, url)
        if result["status"] == "ok":
            results["ok"] += 1
        else:
            results["error"] += 1
            results["errors"].append(result)

        if (i + 1) % 10 == 0:
            print(f"  Submitted {i + 1}/{len(all_urls)} ({results['ok']} ok, {results['error']} errors)")

        time.sleep(BATCH_DELAY)

    print(f"\nDone. Submitted {results['ok']} URLs successfully, {results['error']} errors.")
    if results["errors"]:
        print("Errors:")
        for err in results["errors"][:10]:
            print(f"  {err['url']}: {err['error']}")


def cmd_submit(url):
    """Submit a single URL."""
    from googleapiclient.discovery import build

    creds = get_credentials()
    service = build("indexing", "v3", credentials=creds)

    result = submit_url(service, url)
    if result["status"] == "ok":
        print(f"Submitted: {url}")
        print(f"Notify time: {result.get('notifyTime')}")
    else:
        print(f"Error submitting {url}: {result['error']}")


def cmd_submit_new(since: str | None = None, advance_watermark: bool = True):
    """Submit only URLs that changed since last run.

    `since` overrides the stored watermark for BACKFILL. This exists because the old
    code advanced `indexing-last-run.json` on every run including total failures, so the
    757 URLs dropped across the 9 nights of 2026-07-29 -> 2026-08-06 fell permanently
    behind the watermark. Refusing to advance on failure (added today) prevents that
    happening again but cannot undo it — recovering those needs an explicit earlier
    window, which is what `--since` provides. Pair it with `--no-advance` so a backfill
    over an old window does not drag the live watermark backwards.
    """
    from googleapiclient.discovery import build
    from pymongo import MongoClient

    state_file = os.path.join(os.path.dirname(__file__), "..", "logs", "indexing-last-run.json")

    # Load last run timestamp
    last_run = None
    if os.path.exists(state_file):
        with open(state_file) as f:
            data = json.load(f)
            last_run = data.get("last_run")
    if since:
        last_run = since
        print(f"BACKFILL MODE — overriding stored watermark with --since {since}")

    uri = os.environ.get("COSMOS_CONNECTION_STRING")
    if not uri:
        print("ERROR: COSMOS_CONNECTION_STRING not set.")
        return

    client = MongoClient(uri, serverSelectionTimeoutMS=10000)
    db = client["Gold_Coast"]
    urls = []

    query = {}
    if last_run:
        from datetime import datetime as dt
        query["last_updated"] = {"$gte": dt.fromisoformat(last_run)}
        print(f"Finding URLs updated since {last_run}...")
    else:
        print("No previous run found. Submitting all URLs (use submit-all for first run).")
        client.close()
        cmd_submit_all()
        # Without this, last_run never persists (indexing-last-run.json is never
        # created), so every nightly run re-hits this branch forever, re-submitting
        # the ENTIRE property catalog (1700+ URLs) and burning the 200/day quota on
        # mostly-already-indexed pages instead of genuinely new listings. Confirmed
        # via logs/google-indexing.log: this branch fired on every run observed,
        # indexing-last-run.json never existed on disk. See fix-history 2026-07-23.
        os.makedirs(os.path.dirname(state_file), exist_ok=True)
        with open(state_file, "w") as f:
            json.dump({"last_run": datetime.now(timezone.utc).isoformat()}, f)
        return

    for suburb in TARGET_SUBURBS:
        try:
            coll = db[suburb]
            # EDITORIAL GATE (see get_property_urls): never submit a for-sale page
            # to Google until its editorial has been published, so the FIRST time
            # Google sees the page it already has the real meta title + description.
            for doc in coll.find({**query, "listing_status": "for_sale", "ai_analysis.status": "published"}, {"_id": 1}):
                urls.append(f"{SITE_URL}/property/{doc['_id']}")
            for doc in coll.find({**query, "listing_status": "sold"}, {"_id": 1}):
                urls.append(f"{SITE_URL}/sold/{doc['_id']}")
        except Exception as e:
            print(f"  Warning: error querying {suburb}: {e}")

    client.close()

    if not urls:
        print("No new/changed URLs since last run.")
    else:
        print(f"Found {len(urls)} new/changed URLs.")
        creds = get_credentials()
        service = build("indexing", "v3", credentials=creds)

        ok = 0
        errors = []
        for i, url in enumerate(urls[:DAILY_QUOTA]):
            result = submit_url(service, url)
            if result["status"] == "ok":
                ok += 1
            else:
                errors.append({"url": url, "error": result.get("error", "unknown")})
            if (i + 1) % 10 == 0:
                # Progress used to print the ATTEMPT count, so a run failing every
                # single call still read as "Submitted 10/88 … 20/88" and only the
                # final line revealed 0. Show successes against attempts.
                print(f"  {ok} ok / {i + 1} attempted of {len(urls)}")
            time.sleep(BATCH_DELAY)
        print(f"Submitted {ok}/{len(urls)} URLs.")

        # NAME THE CAUSE. cmd_submit_all already does this; this path threw the error
        # string away, which is why 9 consecutive nights of total failure (757 URLs)
        # looked like silence. See fix-history [INDEXING-SILENT-ZERO].
        if errors:
            print(f"{len(errors)} error(s). First 10:")
            for err in errors[:10]:
                print(f"  {err['url']}: {err['error']}")

        if ok == 0:
            # Do NOT advance the watermark: that is what made each night's failure
            # permanent, since the next run's "new/changed since last_run" window
            # excluded everything this run just dropped. Leaving it unchanged means
            # the next run retries the same set.
            print(f"REFUSING to advance the watermark — 0 of {len(urls)} submitted. "
                  f"These URLs stay in the next run's window.")
            raise RuntimeError(
                f"Google Indexing API accepted 0 of {len(urls)} URLs. "
                f"First error: {errors[0]['error'] if errors else 'none captured'}")

    # Save state — only reached when submissions succeeded (or there was nothing to do).
    # A backfill must NOT touch the watermark: it operates on an old window, and writing
    # `now` would skip everything between that window and the real last run.
    if not advance_watermark:
        print("Watermark left unchanged (--no-advance).")
        return
    os.makedirs(os.path.dirname(state_file), exist_ok=True)
    with open(state_file, "w") as f:
        json.dump({"last_run": datetime.now(timezone.utc).isoformat()}, f)


def cmd_status():
    """Check indexing status using Search Console API."""
    from googleapiclient.discovery import build

    creds = get_credentials()
    service = build("searchconsole", "v1", credentials=creds)

    # The DOMAIN property does not exist — Search Console offers DNS verification for
    # `sc-domain:fieldsestate.com.au`, which means it was never created. The verified
    # property is the URL-prefix form, confirmed 2026-08-08 via sites().list():
    #   https://fieldsestate.com.au/ -> siteFullUser
    # Trailing slash is significant; the API matches the verified string exactly.
    # `scripts/brain2/seo_landing_performance.py:35` already probes both forms in order,
    # which is why its GSC pull kept working while this one silently used a property that
    # does not exist.
    site_url = "https://fieldsestate.com.au/"
    # Try URL prefix if domain property doesn't work
    try:
        result = service.searchanalytics().query(
            siteUrl=site_url,
            body={
                "startDate": "2026-03-01",
                "endDate": "2026-03-10",
                "dimensions": ["page"],
                "rowLimit": 25,
            }
        ).execute()
    except Exception:
        site_url = "https://fieldsestate.com.au/"
        result = service.searchanalytics().query(
            siteUrl=site_url,
            body={
                "startDate": "2026-03-01",
                "endDate": "2026-03-10",
                "dimensions": ["page"],
                "rowLimit": 25,
            }
        ).execute()

    rows = result.get("rows", [])
    if not rows:
        print("No search analytics data yet. Google needs a few days to collect data after indexing.")
        return

    print(f"Search Console data for {site_url}:")
    print(f"{'Page':<60} {'Clicks':>7} {'Impressions':>12} {'CTR':>8} {'Position':>10}")
    print("-" * 100)
    for row in rows:
        page = row["keys"][0]
        clicks = row.get("clicks", 0)
        impressions = row.get("impressions", 0)
        ctr = row.get("ctr", 0)
        position = row.get("position", 0)
        print(f"{page:<60} {clicks:>7} {impressions:>12} {ctr:>7.1%} {position:>10.1f}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    load_env()

    if len(sys.argv) < 2:
        print("Usage: python3 scripts/google_indexing.py <command>")
        print("Commands: auth, submit-all, submit <url>, submit-new, status")
        print("  submit-new [--since ISO8601] [--no-advance]   # --since backfills an "
              "older window; pair with --no-advance so it does not move the live watermark")
        sys.exit(1)

    command = sys.argv[1]
    since_arg = None
    if "--since" in sys.argv:
        since_arg = sys.argv[sys.argv.index("--since") + 1]
    no_advance = "--no-advance" in sys.argv

    if command == "auth":
        cmd_auth()
    elif command == "submit-all":
        cmd_submit_all()
    elif command == "submit":
        if len(sys.argv) < 3:
            print("Usage: python3 scripts/google_indexing.py submit <url>")
            sys.exit(1)
        cmd_submit(sys.argv[2])
    elif command == "submit-new":
        # Rule 7: this is the nightly cron path and had NO heartbeat, which is the only
        # reason 9 straight nights of zero submissions went unnoticed. job_run records
        # error + traceback on the raise added in cmd_submit_new and re-raises.
        sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__))))
        from job_status import job_run
        with job_run("google_indexing_submit_new", cadence_hours=24,
                     title="Google Indexing API — new/changed URLs") as beat:
            beat.detail = "submit-new"
            cmd_submit_new(since=since_arg, advance_watermark=not no_advance)
    elif command == "status":
        cmd_status()
    else:
        print(f"Unknown command: {command}")
        sys.exit(1)
