#!/usr/bin/env bash
# The outro runs the SAME files in the preview and in production. This copies the
# iterated versions into the website's public/ folder. Run it after any change to
# outro/*.js or the crack artwork — otherwise the preview and the live deck drift
# apart silently, which is the whole class of bug this project keeps hitting.
set -euo pipefail
SRC="$(cd "$(dirname "$0")" && pwd)"
DEST=/home/fields/Feilds_Website/01_Website/public/off-market-v3
mkdir -p "$DEST/voice" "$DEST/audio"
cp "$SRC"/outro/*.js "$SRC"/outro/cracked-glass*.png "$SRC"/outro/glass_pieces*.json "$DEST/"
cp "$SRC"/outro/voice/*.mp3 "$SRC"/outro/voice/index.json "$DEST/voice/"
cp "$SRC"/audio/nasa/saturn-radio.mp3 "$DEST/audio/"
rm -f "$DEST/glass_pieces_preview.png"          # debug artifact, never shipped
echo "synced $(ls "$DEST"/*.js | wc -l) scripts + assets -> $DEST ($(du -sh "$DEST" | cut -f1))"
echo "NOTE: outro.css is NOT synced — it is generated by splitting deck.css and"
echo "      lives only in the website. Re-split if the outro's styles change."
